### ISSUE TITLE
Add external libraries to generated codepens

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetifyjs.com#219]
Some examples use external libraries such a vee-validate, which causes the generated codepens to not work as they only have vue and vuetify.

**Comment by bdeo** [comment]
I’ve worked out how to inject these dependencies into the codepen but now need to dynamically generate global Vue.use() statements. I’ll be submitting a PR in the next day or so.

**Comment by KaelWD** [comment]
Does your solution work with fonts too? There are some icon examples that need MDI or font-awesome to work.

**Comment by bdeo** [comment]
My solution can be easily tweaked to solve css libs as well. I will add this functionality.

**Comment by bdeo** [comment]
Running into issues here. I've gotten the codepen generated in such a way that it's a normally formatted file, with custom imports at the top, followed by any Vue.use() statements, with the Vue instance at the bottom. However, with vuelidate (for example), the import statements need to be different than how they are normally in the built docs repo. This is causing some issues because there's no way to systematically know what the import needs to be for each library. I'm still working through this and exploring solutions in the meantime. However, simpler libraries like Vee-validate and font-awesome icons/mdi icons are all working correctly.
