### ISSUE TITLE
Better explanation on how to import icons

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#62]
That is the most frequent question.

Font Awesome and MDI icons can have some import code and a link to how to include the library.

**Comment by nekosaur** [comment]
I honestly feel like this is slightly outside the scope of the framework. Depending on your project setup and/or use case, you might want to use local icons, a cdn, or other solution. If we include specific instructions on how to add the icon sets then we have to 

1. Provide support for those solutions
2. Make sure they are up to date should they change

**Comment by peluprvi** [comment]
I've seen a lot of support time spent on it.
I think Vuetify doesn't need it's own explanation page, only some more intuitive text.

Today the link to the external resource is only on the library name, and then comes the phrase "Please note that you still need to include the Font Awesome icons in your project.".

A simple solution could be add a link for the "getting started" of the external library page on some area of this text above.
A second solution could be add a warning alert with the external "getting started" link.
Yet another option could be provide a link to an example code.

The most frequent Vuetify support case is when the developer doesn't read or saw that the external library needs to be imported.
The second most frequent is when the developer doesn't know how or where to import them.

**Comment by bdeo** [comment]
I agree with @nekosaur. This feels a bit out of scope. Importing these icons is similar to including them in other projects, generally speaking. I think that what documentation there is on fa- or mdi- icons is sufficient.

In the case of Font awesome, there is now 2 versions of FA and FA5 has various different ways to include them.

It should be up to the developer to figure this out and (for lack of a better term) develop a solution that best fits for them. Vuetify shouldn't need to lay this out. 

I could see a community guide written by a community member, however.

**Comment by Chimba123** [comment]
I agree with peluprvi Vuetify could improve the explanation other frameworks provide a thorough guide. Vuetify should not fall less. Because in my case when the project is built into a dist folder the fontawesome icons are disappearing! and the makers of Vuetify have no proper guide on this.
 Any simple issue in my case seems like Vuetify has a problem it is not a smooth framework I am beginning to dislike it. I spend more time solving a bug than developing

**Comment by Chimba123** [comment]
I disagree with nekosaur not every developer is a professional. There should be a basic but thorough guide looking at the fact that all developers use fontawesome nowadays it is no excuse for Vuetify it should thoroughly explain itself.

**Comment by johnleider** [comment]
I will re-open this as I think your side of the argument has merit, but we will still greatly appreciate a contribution on this one.

**Comment by Chimba123** [comment]
Thanks but am going back to bootstrap and jquery mobile your framework
needs help I'll get back when the docs especially about basic things
improves its affecting productivity we cannot be debugging something as
basic as icons and footers they should be automatic

Regards

**Comment by johnleider** [comment]
Good luck!

**Comment by Chimba123** [comment]
Solved it vuetify comes with the Vue-PWA boilerplate meaning webpack is
involved.

When you include the downloaded font awesome fonts and its CSS In your
project by referencing it in the entry js file font awesome will work
properly during development the problem comes when you build the project it
jumbles up the minified files such that the reference to the fonts folder
is disturbed/untrue relative to itself.

Thus you have to look into the minified css file and check how it's
referencing the fonts folder relative to itself.



Regards

**Comment by paanoop** [comment]
Vuetify has an excellent document regd this. Please refer https://vuetifyjs.com/en/framework/icons
