### ISSUE TITLE
[Bug Report] slider event parameters

### ISSUE THREAD

**Issue by damylen** [vuetifyjs/vuetifyjs.com#659]
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.67
**OS:** Windows 10

### Steps to reproduce
<v-slider v-model="layer.opacity" max="100" min="0" @change="layerOpacityChanged(layer)"></v-slider>

### Expected Behavior
No exception, or the option to use:
layerOpacityChanged($value, layer)

### Actual Behavior
Although the layerOpacityChanged is call with the correct layer information, this event will trigger an exception:
[Vue warn]: Error in event handler for "change": "TypeError: Cannot read property 'value' of undefined"

### Reproduction Link
[https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VSlider/VSlider.js](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VSlider/VSlider.js)

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by KaelWD** [comment]
This repository is for documentation-related issues only
The correct vue syntax (which has nothing to do with vuetify) is `$event`
A link to our source is not a valid reproduction, especially when you're reporting a problem with your own code
